// Re-exports for convenience — import from here, not from types/database.ts directly
export type { Database, Json } from "@/types/database";
export type {
  UserRole,
  SpecialtyType,
  PriorityLevel,
  ReportStatus,
  LeaveStatus,
  DisputeResolution,
  CrossDistrictStatus,
  EscalationType,
  NotificationType,
  PhotoType,
  GenderType,
  Profile,
  District,
  Category,
  Report,
  ReportPhoto,
  ReportFeedback,
  ReportDispute,
  LeaveRequest,
  CrossDistrictRequest,
  Notification,
  Escalation,
  DailySummary,
  ProfileInsert,
  ReportInsert,
  NotificationInsert,
  TechnicianWorkload,
  DistrictStats,
  HeatmapPoint,
  NearbyReport,
  LeastBusyTechnician,
  ReportWithDetails,
  ProfileWithDistrict,
} from "@/types/domain";

export { ROLE_DASHBOARDS, ALL_REPORT_STATUSES, ALL_PRIORITY_LEVELS, ALL_SPECIALTIES, ALL_USER_ROLES } from "@/types/domain";
